---
# tasks file for java

- name: apt-get update
  apt: update_cache=yes cache_valid_time=600
  become: yes
  become_user: root
- name: jdk install
  apt: name=default-jdk
  become: yes
  become_user: root
- name: Check java version
  shell: java -version
  register: java_result
- debug: 
    msg: "Java Version: {{ java_result.stderr }}"
